
import com.excellentsystem.jagobangunpersadafx.DAO.HutangDAO;
import com.excellentsystem.jagobangunpersadafx.DAO.KeuanganDAO;
import com.excellentsystem.jagobangunpersadafx.DAO.PembangunanDetailDAO;
import com.excellentsystem.jagobangunpersadafx.DAO.PembangunanHeadDAO;
import com.excellentsystem.jagobangunpersadafx.DAO.PembayaranDAO;
import com.excellentsystem.jagobangunpersadafx.DAO.PropertyDAO;
import com.excellentsystem.jagobangunpersadafx.DAO.SKLHeadDAO;
import com.excellentsystem.jagobangunpersadafx.Koneksi;
import static com.excellentsystem.jagobangunpersadafx.Main.tglBarang;
import static com.excellentsystem.jagobangunpersadafx.Main.tglSql;
import com.excellentsystem.jagobangunpersadafx.Model.Hutang;
import com.excellentsystem.jagobangunpersadafx.Model.Keuangan;
import com.excellentsystem.jagobangunpersadafx.Model.PembangunanDetail;
import com.excellentsystem.jagobangunpersadafx.Model.PembangunanHead;
import com.excellentsystem.jagobangunpersadafx.Model.Pembayaran;
import com.excellentsystem.jagobangunpersadafx.Model.Property;
import com.excellentsystem.jagobangunpersadafx.Model.SKLHead;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Excellent
 */
public class Main extends javax.swing.JFrame {
    private static void insertKeuangan(Connection con, String noKeuangan, String tanggal, String tipeKeuangan, 
            String kategori, String kodeProperty, String deskripsi, double jumlahRp, String kodeUser, 
            String tglInput, String status, String tglBatal, String userBatal)throws Exception{
        Keuangan k = new Keuangan();
        k.setNoKeuangan(noKeuangan);
        k.setTglKeuangan(tanggal);
        k.setTipeKeuangan(tipeKeuangan);
        k.setKategori(kategori);
        k.setKodeProperty(kodeProperty);
        k.setDeskripsi(deskripsi);
        k.setJumlahRp(jumlahRp);
        k.setKodeUser(kodeUser);
        k.setTglInput(tglInput);
        k.setStatus(status);
        k.setTglBatal(tglBatal);
        k.setUserBatal(userBatal);
        KeuanganDAO.insert(con, k);
    }
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        keteranganField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        property1Field = new javax.swing.JTextField();
        tglPembayaranField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipeKeuanganField = new javax.swing.JTextField();
        jumlahRpProperty1Field = new javax.swing.JTextField();
        property2Field = new javax.swing.JTextField();
        jumlahRpProperty2Field = new javax.swing.JTextField();
        property3Field = new javax.swing.JTextField();
        jumlahRpProperty3Field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kategoriField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Insert Pembangunan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Keterangan");

        jLabel3.setText("Property 1");

        jLabel4.setText("Tgl Pembayaran");

        jLabel5.setText("Tipe Keuangan");

        jLabel6.setText("Property 2");

        jLabel7.setText("Property 3");

        jLabel8.setText("Kategori");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keteranganField)
                            .addComponent(tglPembayaranField)
                            .addComponent(tipeKeuanganField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(property3Field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(property2Field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(property1Field, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahRpProperty1Field)
                                    .addComponent(jumlahRpProperty2Field)
                                    .addComponent(jumlahRpProperty3Field)))
                            .addComponent(kategoriField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keteranganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(property1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahRpProperty1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahRpProperty2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(property3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahRpProperty3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglPembayaranField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipeKeuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try(Connection con = Koneksi.getConnection()){
            try{
                con.setAutoCommit(false);
                //insert pembangunan
                PembangunanHead p = new PembangunanHead();
                p.setAllDetail(new ArrayList<>());

                Date tglPembangunan = new Date();
                Property prop1 = PropertyDAO.get(con, property1Field.getText());
                if(prop1!=null){
                    PembangunanDetail d = new PembangunanDetail();
                    d.setKodeProperty(prop1.getKodeProperty());
                    d.setNamaProperty(prop1.getNamaProperty());
                    d.setLuasTanah(prop1.getLuasTanah());
                    d.setBiaya(Double.parseDouble(jumlahRpProperty1Field.getText()));
                    p.getAllDetail().add(d);

                    SKLHead skl = SKLHeadDAO.getByKodeProperty(con, prop1.getKodeProperty(), "true");
                    if(tglSql.parse(skl.getTglSKL()).before(tglPembangunan))
                        tglPembangunan = tglSql.parse(skl.getTglSKL());
                }

                Property prop2 = PropertyDAO.get(con, property2Field.getText());
                if(prop2!=null){
                    PembangunanDetail d = new PembangunanDetail();
                    d.setKodeProperty(prop2.getKodeProperty());
                    d.setNamaProperty(prop2.getNamaProperty());
                    d.setLuasTanah(prop2.getLuasTanah());
                    d.setBiaya(Double.parseDouble(jumlahRpProperty2Field.getText()));
                    p.getAllDetail().add(d);

                    SKLHead skl = SKLHeadDAO.getByKodeProperty(con, prop2.getKodeProperty(), "true");
                    if(tglSql.parse(skl.getTglSKL()).before(tglPembangunan))
                        tglPembangunan = tglSql.parse(skl.getTglSKL());
                }

                Property prop3 = PropertyDAO.get(con, property3Field.getText());
                if(prop3!=null){
                    PembangunanDetail d = new PembangunanDetail();
                    d.setKodeProperty(prop3.getKodeProperty());
                    d.setNamaProperty(prop3.getNamaProperty());
                    d.setLuasTanah(prop3.getLuasTanah());
                    d.setBiaya(Double.parseDouble(jumlahRpProperty3Field.getText()));
                    p.getAllDetail().add(d);

                    SKLHead skl = SKLHeadDAO.getByKodeProperty(con, prop3.getKodeProperty(), "true");
                    if(tglSql.parse(skl.getTglSKL()).before(tglPembangunan))
                        tglPembangunan = tglSql.parse(skl.getTglSKL());
                }

                String noPembangunan = PembangunanHeadDAO.getIdByDate(con, tglPembangunan);
                String noKeuangan1 = KeuanganDAO.getIdByDate(con, tglPembangunan);
                int totalProperty = 0;
                double totalLuasTanah = 0;
                double totalBiaya = 0;
                for(PembangunanDetail d : p.getAllDetail()){
                    d.setNoPembangunan(noPembangunan);
                    PembangunanDetailDAO.insert(con, d);

                    Property prop = PropertyDAO.get(con, d.getKodeProperty());
                    prop.setNilaiProperty(prop.getNilaiProperty()+d.getBiaya());
                    PropertyDAO.update(con, prop);

                    insertKeuangan(con, noKeuangan1, tglBarang.format(tglPembangunan), "ASET LANCAR", "Tanah & Bangunan", d.getKodeProperty(),
                            "Pembangunan - "+noPembangunan, d.getBiaya(), "Yunaz", tglSql.format(tglPembangunan),"true","2000-01-01 00:00:00","");

                    insertKeuangan(con, noKeuangan1, tglBarang.format(tglPembangunan), tipeKeuanganField.getText(), "Pembangunan", d.getKodeProperty(),
                            "Pembangunan - "+noPembangunan, -d.getBiaya(), "Yunaz", tglSql.format(tglPembangunan),"true","2000-01-01 00:00:00","");

                    totalProperty = totalProperty + 1;
                    totalLuasTanah = totalLuasTanah + d.getLuasTanah();
                    totalBiaya = totalBiaya + d.getBiaya();
                }
                p.setNoPembangunan(PembangunanHeadDAO.getIdByDate(con, tglPembangunan));
                p.setTglPembangunan(tglSql.format(tglPembangunan));
                p.setKategori(kategoriField.getText());
                p.setKeterangan(keteranganField.getText());
                p.setMetode("Manual");
                p.setTipeKeuangan(tipeKeuanganField.getText());
                p.setKodeUser("Yunaz");
                p.setStatus("true");
                p.setTglBatal("2000-01-01 00:00:00");
                p.setUserBatal("");
                p.setAllDetail(new ArrayList<>());
                p.setTotalProperty(totalProperty);
                p.setTotalLuasTanah(totalLuasTanah);
                p.setTotalBiaya(totalBiaya);
                PembangunanHeadDAO.insert(con, p);

                //insert hutang
                Hutang h = new Hutang();
                h.setNoHutang(HutangDAO.getIdByDate(con, tglPembangunan));
                h.setTglHutang(tglSql.format(tglPembangunan));
                h.setKategori("Hutang Pembangunan");
                h.setKeterangan(keteranganField.getText());
                h.setJumlahHutang(p.getTotalBiaya());
                h.setPembayaran(p.getTotalBiaya());
                h.setSisaHutang(0);
                h.setJatuhTempo("2000-01-01");
                h.setStatus("close");
                HutangDAO.insert(con, h);

                String noKeuangan2 = KeuanganDAO.getIdByDate(con, tglPembangunan);
                insertKeuangan(con, noKeuangan2, tglBarang.format(tglPembangunan), "HUTANG", h.getKategori(), "",
                        h.getNoHutang()+" - "+h.getKeterangan(), h.getJumlahHutang(), "Yunaz", tglSql.format(tglPembangunan),"true","2000-01-01 00:00:00","");

                insertKeuangan(con, noKeuangan2, tglBarang.format(tglPembangunan), tipeKeuanganField.getText(), h.getKategori(), "",
                        h.getNoHutang()+" - "+h.getKeterangan(), h.getJumlahHutang(), "Yunaz", tglSql.format(tglPembangunan),"true","2000-01-01 00:00:00","");

                //insert pembayaran hutang
                Date tglPembayaran = tglBarang.parse(tglPembayaranField.getText());
                Pembayaran pb = new Pembayaran();
                pb.setNoPembayaran(PembayaranDAO.getIdByDate(con, tglPembayaran));
                pb.setTglPembayaran(tglSql.format(tglPembayaran));
                pb.setNoHutang(h.getNoHutang());
                pb.setJumlahPembayaran(p.getTotalBiaya());
                pb.setTipeKeuangan(tipeKeuanganField.getText());
                pb.setCatatan("");
                pb.setKodeUser("Yunaz");
                pb.setStatus("true");
                pb.setTglBatal("2000-01-01 00:00:00");
                pb.setUserBatal("");
                PembayaranDAO.insert(con, pb);

                String noKeuangan3 = KeuanganDAO.getIdByDate(con, tglPembayaran);
                insertKeuangan(con, noKeuangan3, tglBarang.format(tglPembayaran), "HUTANG", h.getKategori(), "",
                        "Pembayaran - "+h.getNoHutang()+" - "+h.getKeterangan(), -pb.getJumlahPembayaran(), "Yunaz", tglSql.format(tglPembangunan),"true","2000-01-01 00:00:00","");

                insertKeuangan(con, noKeuangan3, tglBarang.format(tglPembayaran), pb.getTipeKeuangan(), h.getKategori(), "",
                        "Pembayaran - "+h.getNoHutang()+" - "+h.getKeterangan(), -pb.getJumlahPembayaran(), "Yunaz", tglSql.format(tglPembangunan),"true","2000-01-01 00:00:00","");


                //rubah hpp
                for(PembangunanDetail d : p.getAllDetail()){
                    Property prop = PropertyDAO.get(con, d.getKodeProperty());
                    SKLHead skl = SKLHeadDAO.getByKodeProperty(con, d.getKodeProperty(), "true");
                    
                    Keuangan hpp = KeuanganDAO.get(con, "HPP", "HPP", d.getKodeProperty(), "Penjualan - "+skl.getNoSKL());
                    hpp.setJumlahRp(prop.getNilaiProperty());
                    KeuanganDAO.update(con, hpp);
                    
                    Keuangan asetLancar =  KeuanganDAO.get(con, "ASET LANCAR", "Tanah & Bangunan", d.getKodeProperty(), "Penjualan - "+skl.getNoSKL());
                    asetLancar.setJumlahRp(-prop.getNilaiProperty());
                    KeuanganDAO.update(con, asetLancar);
                }
                con.commit();
                con.setAutoCommit(true);
            }catch(Exception e){
                con.rollback();
                con.setAutoCommit(true);
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jumlahRpProperty1Field;
    private javax.swing.JTextField jumlahRpProperty2Field;
    private javax.swing.JTextField jumlahRpProperty3Field;
    private javax.swing.JTextField kategoriField;
    private javax.swing.JTextField keteranganField;
    private javax.swing.JTextField property1Field;
    private javax.swing.JTextField property2Field;
    private javax.swing.JTextField property3Field;
    private javax.swing.JTextField tglPembayaranField;
    private javax.swing.JTextField tipeKeuanganField;
    // End of variables declaration//GEN-END:variables
}
